(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[302,159,108,108],[99,252,78,75],[0,252,97,99],[0,0,300,250],[302,0,157,157]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.brussels = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.cranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.mashedtaters = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.tablestillatasteof = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.turkeymealplate = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whole = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape.setTransform(39.3,3.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZBuQgHgCAAgHQAAgFAGgDIAHgEQADgCACgKIABgeIAAgYIgBgcIAAgMQAAgngBgLQgCgLgDgCIgJgDQgKgDAAgFQAAgEADgDQADgCALgEIAUgGIAQgCQAEAAACADQACADAAAHIAAAMQgCA3AAA2IABA1QABALACADIAJAEQAHADAAAGQAAAGgIACQgHADgUAAQgWAAgIgDg");
	this.shape_1.setTransform(25.7,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgWAYghAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUARAAQAQAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_2.setTransform(12,3.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAWBuQgIgCAAgGQAAgGAIgDIAFgCQAEgCABgHQACgGAAgRQAAgxgGgLQgHgNgQAAQgHAAgHAFQgIAFgEAHQgDAHgCAMIgBApQAAAQABAFQACAFADACIAGACQAHADAAAGQAAAGgHACQgIADgTAAQgZAAgHgDQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgGQACgHAAgRIAAgZIAAgXIgBhFQgBgRgDgDQgBgCgJgDQgKgCAAgGQAAgEAEgDQAEgDAOgFIAPgEIAOgCQAFAAADADQACADAAAHIgBAHIgBA9IAAAHIABAEIACABIADgDIAGgGQAIgIAIgEQAIgEAKAAQAaAAANARQANASAAAhIAAAPIAAAbIAAAJQAAAHACAEQABADADACIAEACQAIADAAAFQAAAHgHACQgIADgYAAQgUAAgHgDg");
	this.shape_3.setTransform(-7,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAVA1IgghUQgKgcgGgNQgHgNgFgEIgJgEQgIgDAAgFQAAgHAIgCQAHgCAdAAQAcAAAHACQAHACAAAHQAAAGgLAEIgCAAQgDACgCACQgCACAAADQAAAGAIAVIAZBDIALAYQADAGADAAQACAAADgEIAKgXIADgHQAfhLAAgJQAAgFgCgEQgCgDgFgCIgEgCQgJgEAAgFQAAgHAGgCQAHgCAZAAQAYAAAGACQAHACAAAHQAAAFgJAEIgHAEQgLAGgUA1IgNAgIgdBIIgFANQgKAZgGAAQgIAAgXg8gAg/BkIgCgFQgTgrgehNIgOgmIgKgSQgEgHgEgCIgFgCQgKgDAAgGQAAgHAIgCQAHgCAdAAQAdAAAHACQAHACAAAHQAAAGgMAEIgBAAQgEACgBACQgCACAAADQAAAGAGASIAaBEIAMAcQADAEACAAQADABADgIIAIgSQADgJAJgBQAJAAAAALIgCAJIgUAxIgEAMQgKAZgGAAQgFAAgGgNg");
	this.shape_4.setTransform(-32.7,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.whole, new cjs.Rectangle(-50.5,-20.2,101.2,40.5), null);


(lib.WFM_Logo_White_RGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(175,175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(305.4,234.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(163.9,260);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(305.6,233);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(126.2,205.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(130.7,263.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(239.5,205);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(181.9,205.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,350,350);


(lib.turkeymealplatemc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.turkeymealplate();
	this.instance.parent = this;
	this.instance.setTransform(-78.5,-78.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.turkeymealplatemc, new cjs.Rectangle(-78.5,-78.5,157,157), null);


(lib.trynewsamplesforyourfeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHBdQgIgDgFgFQgGgGgCgIQgCgIAAgXIAAhRIgPAAIgEgCIgBgEIAAgDQAAgGAQgNIAGgGIAGgFQAQgOAGAAIAEABQAAABABAAQAAABAAAAQAAABABAAQAAABAAAAIAAAdIAiAAQAEAAABACIABAFIAAAEIgBAFQgCADgDAAIggAAIgCABIgBADIAABMQAAATADAFQAEAGAJgBQAEAAAIgCIALgDQADABACACQACACAAACQAAAJgNAIQgNAIgQAAQgJAAgHgCg");
	this.shape.setTransform(70.3,18.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_1.setTransform(57.6,20.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcBIIgJgIIgHAEQgSAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQAEADAAAFQAAAJgLAAQgPAAgIAHQgKAHAAANQAAANAIAHQAIAHAOAAQANAAAHgGQAGgHAAgQIAAg6QABgNgHgHQgFgIgKAAQgIAAgGAEQgGADgGAHIgEAEQgJAMgLAAQgGAAgDgEQgEgEAAgHQAAgOASgKQARgKAdAAQAQAAAMAEQANAFAGAIQAFAGACAKQACAJAAAWIAAAxQgBAIACAFQABAEAEABIAEABQAKADAAAFQAAAHgLAGQgKAGgOAAQgGAAgHgIg");
	this.shape_2.setTransform(42.5,20.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_3.setTransform(25.5,20.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOBuQgIgDAAgHQAAgGAIgDQAIgDACgDQACgCABgYIACg7IgCg4QgBgXgCgEQgCgCgIgDQgIgDAAgHQAAgFAIgDQAGgCAbAAIBdAAIAQgCIAHgCIAEABIADADQADAFADALQACALAAAHQAAAHgCAEQgDADgEABQgGAAgGgLIgEgHQgDgFgIgDQgGgCgLAAIgVAAQgNAAgIABQgHACgEAEQgCADgBAKIgBAdIAAANQgBAHACACQABACAFAAIAYAAQAMAAAFgDQAFgEABgKIAAgCQADgQAIgBQAHABACAIQADAIAAAdQAAAdgDAIQgCAJgHgBQgIABgDgRIAAgCQgBgKgFgDQgFgEgMAAIgYAAQgEAAgCADQgCADABAJIAAAMIABArQAAAJADACIAHAEQAKADgBAHQAAAGgIADQgJADgXgBQgZABgJgDg");
	this.shape_4.setTransform(7.9,16.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_5.setTransform(-16.6,20.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAhBOQgCgCAAgFIAAgLIAAgBIgBAAQgCAAgDAEIgCACQgIAHgJAEQgIAEgLAAQgMAAgKgFQgKgEgHgIQgHgJgDgMQgDgMAAggIAAgLIAAgLIAAgDQAAgNgCgDQgCgEgFgCIgGgCQgJgCAAgGQAAgDADgDQADgDALgDIAVgGIAQgCQAEAAACADQACADAAAHIAAAGIgCA5QAAAfAHAMQAGAMAQAAQARAAAHgQQAIgPAAglIAAgMQAAgMgCgDQgCgEgFgCIgGgCQgJgCAAgGQAAgDADgDQADgCALgEIAVgGIAQgCQAEAAACADQACADAAAHIAAAIIgCA/IAAAaIABAKQABAGAIADIADABQAJADAAAFQAAAEgDACIgJAGIgWAHQgLACgFAAQgFAAgCgCg");
	this.shape_6.setTransform(-32.6,20.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgWAYgiAAQggAAgWgXgAgcgtQgKAMAAAVQAAAeANAUQANAUASAAQAOAAAKgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgPAAgJANg");
	this.shape_7.setTransform(-50.7,20.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfBsQgJgDAAgGQAAgHAJgDIAHgEQAFgDABg/IAAgOIgSgdIgdguQgJgNgFgDIgIgEQgKgDAAgGQAAgGAHgDQAHgCAeAAQAeAAAHACQAHADAAAGQAAAGgMAEIgBABIgEADIgCAEQAAAEAHALIAeAvIAagnQAJgOAAgFQAAgEgCgCQgDgDgHgDIgHgEQgCgCAAgEQAAgGAGgDQAGgCAaAAQAYAAAHACQAGADAAAGQAAAGgIAEIgMAGQgHAFgOAWIglA8IAAAbQABAzAEADIAHAEQAJADAAAHQAAAGgIADQgIADgZAAQgXAAgIgDg");
	this.shape_8.setTransform(-69.7,16.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_9.setTransform(-94.6,20.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgWAYghAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUARAAQAQAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_10.setTransform(-109.9,20.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgqBuQgIgCAAgGQAAgFAHgDIAEgCQAEgCABgEQACgFAAgNIAAgPIAAhJIgRAAQgEAAgBgDQgCgBAAgEIAAgEQAAgDACgCQABgCAEAAIAQAAIgBgMIgBgLQAAgXAOgOQAOgMAZAAQARAAALAHQALAJAAAMQAAAHgEAEQgEADgIAAQgEAAgEgCQgEgCgDgEIgDgFQgFgMgJAAQgGAAgDAEQgDAEAAAGIADARQADANAAALIAWAAQAEAAACACQABABAAAEIAAAEQAAAEgBABQgCADgEAAIgWAAIAABNQAAAUACAGQABAGADABIAGADQAJADAAAGQAAAGgIACQgHACgWABQgWgBgHgCg");
	this.shape_11.setTransform(-122.1,16.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_12.setTransform(103.6,-13.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_13.setTransform(91,-13.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgXAYggAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUASAAQAOAAAKgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_14.setTransform(75.7,-13.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgQBBQgJgPgVgzIgJgWQgLgdgHgEIgEgCQgJgEAAgFQAAgHAIgCQAHgDAZABQAVgBAIADQAHACAAAHIgBAFIgDADIgFABQgGAEAAADIADALIAMAeIAMAeQAEAHACAAQACgBADgEIAGgNIARgmQAFgPAAgFIgBgGIgDgDIgFgCQgHgDAAgFQAAgFAHgDQAHgDATABQAQgBAHADQAGADAAAFQAAAHgIACIgFACQgHAEgNAeIgEAJIgGAOQgjBPgJAAQgHAAgJgOg");
	this.shape_15.setTransform(58.6,-12.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAbBIIgIgIIgGAEQgTAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQADADAAAFQABAJgKAAQgPAAgKAHQgJAHAAANQAAANAIAHQAIAHANAAQAPAAAGgGQAHgHAAgQIAAg6QgBgNgFgHQgGgIgKAAQgIAAgGAEQgGADgHAHIgDAEQgJAMgKAAQgHAAgEgEQgDgEAAgHQAAgOASgKQARgKAcAAQARAAAMAEQANAFAGAIQAEAGACAKQACAJAAAWIAAAxQAAAIACAFQABAEADABIAGABQAJADAAAFQAAAHgKAGQgKAGgOAAQgHAAgIgIg");
	this.shape_16.setTransform(42.1,-13.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgZBuQgHgCgBgHQABgFAGgDIAIgEQACgCABgKIABgeIAAgYIAAgcIAAgMQAAgngBgLQgCgLgCgCIgKgDQgKgDAAgFQAAgEADgDQADgCALgEIAVgGIAOgCQAFAAACADQACADAAAHIgBAMQgBA3AAA2IABA1QABALADADIAIAEQAHADAAAGQAAAGgIACQgHADgUAAQgXAAgHgDg");
	this.shape_17.setTransform(28.7,-16.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhOBuQgIgDAAgHQAAgGAIgDQAIgDACgDQACgDABgWIACg8IgCg4QgBgYgCgCQgCgCgIgEQgIgEAAgGQAAgFAIgDQAGgCAbAAIBdAAIAQgCIAHgCIAEACIADACQADAGADAKQACALAAAHQAAAHgCAEQgDAEgEgBQgGAAgFgKIgFgIQgDgEgIgDQgGgCgLAAIgVAAQgNAAgIABQgHACgEAEQgCADgBAKIgBAeIAAAMQgBAHACACQABACAFAAIAYAAQAMAAAFgDQAFgEABgKIAAgDQADgQAIAAQAHAAACAJQADAIAAAdQAAAdgDAJQgCAHgHABQgIAAgDgQIAAgDQgBgKgFgEQgFgDgMAAIgYAAQgEAAgCADQgCADABAJIAAAMIAAArQABAJADACIAHADQAKAEgBAGQAAAHgIADQgJACgXAAQgZAAgJgCg");
	this.shape_18.setTransform(15.1,-16.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAJAQIgSgvQgJgWgHgDIgEgCQgJgEAAgFQAAgHAHgCQAIgDAYABQAVgBAIADQAHACAAAHIgBAFIgDADIgFABQgGAEAAADIACAKIANAfIANAeQAEAHACAAQACgBADgEIAGgNIARgmQAGgPAAgFIgCgGIgDgDIgFgCQgHgDAAgFQAAgFAHgDQAHgDATABQAQgBAHADQAGADAAAFQAAAHgIACIgFACQgHAEgOAfIgDAIIgHAOQgiBPgLAAQgKAAgbg/gAhZAJIgFgKIgKgZQgKgagHgEIgEgCQgJgEAAgFQAAgHAIgCQAHgDAZABQAVgBAIADQAHACAAAHIgBAFIgDADIgFABQgGAEAAADIADAMIAMAdIANAdQAEAIACAAQAEAAAEgKIAGgLIADgEQACgCADAAQAEAAACACQACADAAADQAAAEgEAJQgQAjgHALQgHAMgFAAQgLAAgehGg");
	this.shape_19.setTransform(-16.3,-12.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_20.setTransform(-37.7,-13.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAOAqIgFgGIghgqIgfgnIgNgPIgBALIAAAVIAAAOQABBCABASQACARAFAAQAEAAAEADQAFAEAAAEQAAAGgHADQgIADgSAAQgSAAgIgDQgHgDAAgGQAAgGAJgDQAIgDABgDQACgCACgWIABg8IgBg6QgCgXgCgCQgBgCgIgEQgJgEAAgFQAAgHAHgCQAHgCAUAAIARABIAFABIAWAbIAfAoIAhApIAZAdIAQASIAAgGIAAgMIgBhLQgBgggCgEIgCgEIgDgCQgIgDgDgCQgCgCAAgEQAAgHAHgCQAGgCAVAAQASAAAHACQAHACgBAHQAAADgCACIgFAEIgEABQgGADgBAEQgCAGgBAeIgBBcIAAAdIABATQAAAMgBACQgCADgFAAQgPAAg3hFg");
	this.shape_21.setTransform(-58.2,-16.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhGBmQgIgHAAgJQABgIAFgGQAFgFAIAAIAGABIAGADIADAGQAFAGADAAQAHAAAJgLQAHgLAAgMQAAgNgLgZIgBgEIgZg1IgNgdQgDgGgKgEQgFgCgBgCQgCgCgBgDQABgIAHgCQAJgDAWAAQAXAAAHADQAHACABAHIgBAEIgDADIgFADQgHACAAACIAEAMIAMAfIALAcQAEAIADAAQACAAADgIIAKgYIALgeQAEgLAAgEQAAgEgJgFQgIgFgBgEQABgFAGgCQAIgDARAAQATAAAGADQAHACgBAHQAAAFgJACIgFADQgKAEgJAaIgFAMIgUAxQgZBAgPASQgQAUgXAAQgLAAgHgGg");
	this.shape_22.setTransform(-87.3,-10.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_23.setTransform(-101.2,-13.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AggBtQgIgDgBgGQAAgHAJgDQAJgDABgCQACgDABgZIABhIIgBgoIgBgZQgBgEgDgBQgCgCgHAAIgGAAQgLAAgFADQgHACgDAGIgGAKIgEALIgFAFQgCACgDAAQgEAAgCgEQgCgFAAgJQgBgUAFgNQAFgMAHAAIACAAQAMACASAAIBaAAQASAAANgCIACAAQAHAAAFAMQAFANAAAUQgBAJgCAEQgCAFgEAAIgGgCIgEgFIgFgLIgFgKQgDgGgHgCQgFgDgMAAIgFAAQgHAAgCACQgDABgBAEIgBAZIgBAoIABBIQABAZACADQACACAIADQAIADAAAHQAAAGgIADQgJADgYAAQgXAAgJgDg");
	this.shape_24.setTransform(-117.8,-16.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-129.8,-36.9,242.8,73.9);


(lib.tophead = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBvQgIgDAAgGQAAgFAHgDIAEgBQAEgDABgEQACgFAAgNIAAgQIAAhJIgRAAQgEAAgBgBQgCgCAAgEIAAgEQAAgEACgCQABgBAEAAIAQAAIgBgMIgBgLQAAgYAOgNQAOgNAZAAQARAAALAJQALAHAAAMQAAAIgEADQgEAFgIAAQgEgBgEgCQgEgCgDgEIgDgGQgFgLgJAAQgGAAgDAEQgDAEAAAGIADARQADAOAAAKIAWAAQAEAAACABQABACAAAEIAAAEQAAAEgBACQgCABgEAAIgWAAIAABPQAAATACAGQABAGADACIAGACQAJADAAAGQAAAGgIADQgHACgWAAQgWAAgHgCg");
	this.shape.setTransform(71.8,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgWAYghAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUARAAQAQAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_1.setTransform(56.6,3.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_2.setTransform(29.3,3.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHBcQgIgCgFgGQgGgFgCgHQgCgJAAgXIAAhSIgPAAIgEgBIgBgEIAAgEQAAgEAQgOIAGgGIAGgFQAQgOAGAAIAEABQAAABABAAQAAABAAAAQABABAAAAQAAAAAAABIAAAdIAiAAQAEAAABABIABAGIAAAEIgBAGQgCABgDAAIggAAIgCABIgBAEIAABLQAAAVADAFQAEAEAJAAQAEAAAIgCIALgCQADAAACABQACACAAAEQAAAIgNAIQgNAIgQAAQgJAAgHgDg");
	this.shape_3.setTransform(14.9,2.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_4.setTransform(1.7,3.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBIIgIgIIgHAEQgSAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQADADABAFQgBAJgJAAQgPAAgKAHQgJAHAAANQAAANAIAHQAIAHANAAQAPAAAGgGQAHgHgBgQIAAg6QAAgNgFgHQgGgIgKAAQgIAAgGAEQgHADgFAHIgEAEQgJAMgLAAQgGAAgEgEQgDgEAAgHQAAgOASgKQASgKAcAAQAQAAAMAEQAMAFAHAIQAEAGACAKQACAJAAAWIAAAxQABAIABAFQACAEADABIAEABQAKADAAAFQAAAHgLAGQgJAGgOAAQgHAAgIgIg");
	this.shape_5.setTransform(-13.9,3.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggBtQgIgDgBgGQAAgHAJgDQAJgDABgCQACgDABgZIABhIIgBgoIgBgZQgBgEgDgBQgCgCgHAAIgGAAQgLAAgFADQgHACgDAGIgGAKIgEALIgFAFQgCACgDAAQgEAAgCgEQgCgFAAgJQgBgUAFgNQAFgMAHAAIACAAQAMACASAAIBaAAQASAAANgCIACAAQAHAAAFAMQAFANAAAUQgBAJgCAEQgCAFgEAAIgGgCIgEgFIgFgLIgFgKQgDgGgHgCQgFgDgMAAIgFAAQgHAAgCACQgDABgBAEIgBAZIgBAoIABBIQABAZACADQACACAIADQAIADAAAHQAAAGgIADQgJADgYAAQgXAAgJgDg");
	this.shape_6.setTransform(-33.2,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAiBuQgKgDAAgHQAAgFALgEIACgBQAFgCACgCQABgCAAgEIgCgMIgGgRIgCgEIgDgCIgMgBIgWAAIgOAAQgNAAAAgLQAAgMANAAIAIAAIAQAAIAQABIgQgqIgPgkIgEAAIgQAnIgPAnIgPAnQgDAJAAAGQAAAEABAEQADADAEACIAGACQAJADAAAGQAAAHgIADQgIADgWAAQgYAAgIgDQgIgDAAgHQABgGAIgDIAHgDQALgHAKgbIAEgJIAWg2IAGgOQAVg3AGgXQABgHADgCQAEgCAJAAQAEAAAEACQADADADAFIAXAzIAeBIIAHASQASAtAKAFIAGACQAKADAAAGQAAAHgKADQgJADgbAAQgcAAgIgDg");
	this.shape_7.setTransform(-64.7,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tophead, new cjs.Rectangle(-78,-20.2,156.1,40.5), null);


(lib.tastingeventmc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOArQgHgDgGgFQgFgFgDgHIgCgHIgBgIIAAgXIAAgZIABgCIADgCIAEAAIACAAIAEABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAtQAAAFACAEQABAFADAEQADADAEACQAFACAEAAQAGAAAEgCQAEgCADgDQADgEABgFQACgEAAgFIAAgtQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIAEgBIADgBIADABIADABIABADIAAAwIgBAIIgCAHQgDAHgFAFQgGAFgHADQgHADgIAAQgHAAgHgDg");
	this.shape.setTransform(83.7,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIAtIgJgDIgIgEIgHgGQgHgFgDgJIgDgIIgBgKIABgIIADgJQADgJAHgGIAHgFIAIgEIAJgDIAIgBIAKABIAJADQAIAEAGAFQAHAGAEAJQADAIAAAJIgBAKIgCAIQgEAJgHAFQgGAHgIADIgJADIgKABIgIgBgAgKgbQgGACgEAEQgEAFgDAFQgCAGAAAFQAAAHACAFQADAGAEADQAEAEAGADQAFACAFABQAGgBAFgCQAGgDAEgEQAEgDADgGQACgFAAgHQAAgFgCgGQgDgFgEgFQgEgEgGgCQgFgCgGgBQgFABgFACg");
	this.shape_1.setTransform(73.3,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgBAuIgBAAIgCAAIgCgCIgBgCIAAgeIgBgGIgCgEIgagnIAAgBIABgCIADgCIADgCIADgBIAEABIABACIASAdIABABIACAAIACAAIACgBIASgdIACgCIACgBIAEAAIACACIADACIABACIAAABIAAABIgZAnIgDAFIAAADIAAABIAAAfQgBADgDABg");
	this.shape_2.setTransform(63.8,-0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAWAtIgCgBIgBgBIgCgBIgPgXIgCgDIgEgBIgKAAIgEABIgCADIABAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCABIgEABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgBAAAAIAAhQQAAgBABAAQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAkAAQAHAAAFACQAGADAFADQAEAEACAGQADAFAAAHQgBAIgDAEQgCAEgDADIgGAFQgBAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAIAAACIADAFIAFAHIAFAHIACAFIgBACIgDACIgEABIgCABgAgSgbQAAAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAAUQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABIAFAAIARAAIAHAAIAEgDQADgBABgDQABgDABgEQAAgHgGgEIgEgCIgHgBIgRAAIgFABg");
	this.shape_3.setTransform(51.3,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_4.setTransform(41.8,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdAsIgDgBIgBgCIAAhRQAAAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBIA9AAIACACIABACIAAAEIAAACIAAADIgDACIgsAAIgDACIgBADIAAALIABAEIADABIAdAAIACABIABACIAAAEIAAACQAAAEgEAAIgcAAIgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAsAAQADABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_5.setTransform(33.4,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAaAuQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgjgxIgDgBIgCABIgBACIAAAtIgDADIgFABIgFAAQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhSIABgDIACgBIADgBIADAAQAEABACADIAjAuIACABIACAAIABgBIAAgtIACgCIADgBIADAAIADAAQAEAAABADIAABUIgCADIgEABg");
	this.shape_6.setTransform(23.8,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_7.setTransform(11.1,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAaAuQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgjgxIgDgBIgCABIgBACIAAAtIgDADIgFABIgFAAQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhSIABgDIACgBIADgBIADAAQAEABACADIAjAuIACABIACAAIABgBIAAgtIACgCIADgBIADAAIADAAQAEAAABADIAABUIgCADIgEABg");
	this.shape_8.setTransform(2.6,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIABACIAAAEIAAACIgBADIgCACIguAAIgCACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAtAAQACABAAADIABAEIgBADIgBADIgCABg");
	this.shape_9.setTransform(-6.2,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAArIgEgGIgDgKIgHgMIgGgOIgFgNIgGgMIgDgJIgBgEIABgDIACgCIAEgBIADAAIADABIACADIASArIACABIAAABQAAAAABAAQAAAAABAAQAAAAAAgBQAAAAAAgBIASgsQABAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIAEgBIACAAIAEABIADACIABADIgBAEIgFAJIgEAMIgHANIgGAPIgFANIgFAKIgCAFIAAABIgCABQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBg");
	this.shape_10.setTransform(-15.1,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIABACIABACIAAAEIAAACIAAADIgCACIgtAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgEAAIgbAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAtAAQACABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_11.setTransform(-23.1,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgHAtIgIgDIgIgDIgIgGIgFgHIgFgHQgDgJAAgKIAAgIIADgJQAEgJAGgGIAIgFIAIgEIAIgDIAJgBQAFAAAFACIAKACQAJAFAHAHIAAACIgBADIgDADIgDACIgDACIgEgCIgFgEIgHgFQgEgCgGAAQgFABgGACQgFACgEAEQgFAFgCAFQgCAGAAAFQAAAGACAGQACAFAFAEQAEAEAFADQAGACAFABIAGgBIAGgBIAGgEQACgBACgDIAAgBIgBgDIgDgBIgQAAIgCgBIgBgDIAAgDIAAgDIAAgDQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAlAAIABABIABABQACADAAAFIAAADIgBAEIgHAMQgEAFgGAEQgFADgHACQgGACgHAAIgJgBg");
	this.shape_12.setTransform(-37.5,-0.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAaAuQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgjgxIgDgBIgCABIgBACIAAAtIgDADIgFABIgFAAQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhSIABgDIACgBIADgBIADAAQAEABACADIAjAuIACABIACAAIABgBIAAgtIACgCIADgBIADAAIADAAQAEAAABADIAABUIgCADIgEABg");
	this.shape_13.setTransform(-47.5,-0.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAAAuIgCAAQgEAAgBgDIAAhUIACgCIADgBIACAAIADAAQAEAAABADIAABTIgCADIgDABg");
	this.shape_14.setTransform(-54.3,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_15.setTransform(-60.2,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgTAqQgKgDgHgHIgBgCIAAgBIABgDIADgDIADgCIADgBIAEABIAGAEIAHAEQAEABAGAAIAGAAIAHgCIAFgEQACgDAAgEQAAgDgCgCQgDgDgDgBIgKgBIgJgCIgKgCQgFgBgEgCQgEgDgDgEQgCgFAAgGQAAgHADgFQAEgFAFgEQAFgDAHgBIALgCIAJABIAIACIAJADIAHAFIAAACIABABIgBADIgDADIgDACIgEABIgCAAQgFgEgFgDQgFgCgGAAIgGAAIgGACIgEAEQgCACAAAEQAAAFAEACIAKADIANACQAHABAHACQAGADAEADQAFAFAAAJQgBAIgDAGQgEAFgFAEQgGADgHACIgMACQgKAAgJgEg");
	this.shape_16.setTransform(-68.4,-0.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_17.setTransform(-77.3,-0.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_18.setTransform(-85.5,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tastingeventmc, new cjs.Rectangle(-91.1,-8.4,182.2,16.9), null);


(lib.tablestillatasteof_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.tablestillatasteof();
	this.instance.parent = this;
	this.instance.setTransform(-150,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-125,300,250);


(lib.subhead = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag4BkQgUgMAAgQQAAgIAFgGQAEgEAIAAQAGgBAEAEQAEAEACAHQADALAKAHQAJAGATAAQAUABANgJQAOgHAAgNQAAgHgFgDQgFgFgKAAIgSABIgWACQgcAAgPgJQgOgKAAgMQAAgHAFgIQAFgHAMgGQgKgIgEgKQgEgKAAgLQAAgZASgRQATgRAdAAIAPABIAYAFQAGAAAGgDIARgJIAFAFIACAFQgBAGgFAHQgFAFgIAFIAEAMIACANQAAAZgTAQQgSAQgdgBIgRgBIgPgCIgEAFIgBAGQAAAHAGADQAIAEAPAAIAXgCIAXgCQAWAAAMAJQALAJgBAQQAAAZgYAQQgYAQgjAAQgdAAgUgMgAgYhMQgJALABAOQAAARAHAJQAIAJAMAAQAMAAAJgJQAJgKAAgPQAAgQgJgKQgIgJgMgBQgNABgHAJg");
	this.shape.setTransform(91,6.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhLBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQABgFAAgMIAAgKIAAgNIAAgOQAAgZgBgHQgBgHgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAGgCIAXgHIAPgDQAFAAACACQACADAAAFIAAAKIAAABIABABIABAAIAAgBIAEgDIADgDQARgQASAAQALAAALAFQAKAFAHAIQAHAJADALQADAMAAAZIAAATIAAALIgBAIQAAALACAFQACAEADACIAEACQAIADAAAFQAAAHgHACQgHACgYAAQgVAAgIgCQgHgCAAgGQAAgGAIgDIAFgCQAEgCABgHQACgHAAgQQAAgwgGgNQgHgMgQAAQgHAAgHAFQgIAFgEAIQgDAHgCAMQgBALAAAeQAAAPABAFQABAFAEACIAFACQAIADAAAGQAAAGgHACQgIADgUAAQgXAAgIgDg");
	this.shape_1.setTransform(72.2,3.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAEgBQAEgCACgGQACgFgBgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgHgCQgKgDABgFQgBgEADgCQADgDAGgDIAYgHIAPgDQAEAAACADQACADAAAHIAAAJIgBAHIgBAmIAAABIAAAmQAAAOABAGQABAGAEACIAFADQAIADAAAFQABAGgIADQgIACgUAAQgWAAgIgCgAgShNQgHgFAAgIQAAgJAHgGQAIgGAKAAQAJAAAHAGQAGAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgGgGg");
	this.shape_2.setTransform(57.7,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgQBBQgJgQgVgxIgJgXQgLgegHgDIgEgCQgJgEAAgFQAAgHAIgCQAHgDAZABQAVgBAIADQAHACAAAHIgBAFIgDACIgFACQgGADAAAEIADALIAMAfIAMAdQAEAHACAAQACAAADgFIAGgNIARgmQAFgPAAgFIgBgFIgDgEIgFgCQgHgDAAgFQAAgFAHgDQAHgDATABQAQgBAHADQAGACAAAGQAAAGgIADIgFACQgHAEgNAeIgEAJIgGAOQgjBQgJAAQgHAAgJgPg");
	this.shape_3.setTransform(44.5,3.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAFgBQADgCACgGQACgFAAgLIAAgLIgBgMIAAgQQAAgYgBgHQgBgHgDgCIgIgCQgIgDgBgFQABgEACgCQADgDAHgDIAXgHIAPgDQAFAAABADQACADAAAHIAAAJIAAAHIgBAmIAAABIgBAmQAAAOACAGQABAGADACIAGADQAHADABAFQAAAGgIADQgIACgTAAQgXAAgIgCgAgThNQgFgFAAgIQAAgJAGgGQAIgGAKAAQAJAAAGAGQAHAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgHgGg");
	this.shape_4.setTransform(31.1,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag4BkQgTgMAAgQQAAgIADgGQAFgEAIAAQAHgBADAEQADAEACAHQAEALAKAHQAKAGASAAQAUABAOgJQANgHAAgNQAAgHgFgDQgFgFgKAAIgSABIgXACQgbAAgOgJQgPgKAAgMQAAgHAFgIQAGgHALgGQgKgIgEgKQgFgKABgLQgBgZAUgRQASgRAdAAIAQABIAXAFQAGAAAHgDIAQgJIAFAFIABAFQAAAGgEAHQgGAFgJAFIAGAMIABANQAAAZgSAQQgUAQgdgBIgQgBIgPgCIgEAFIgCAGQABAHAGADQAIAEAPAAIAWgCIAZgCQAVAAAMAJQAKAJABAQQAAAZgZAQQgYAQgkAAQgcAAgUgMgAgZhMQgHALAAAOQgBARAIAJQAIAJANAAQAMAAAIgJQAJgKAAgPQAAgQgJgKQgIgJgMgBQgNABgIAJg");
	this.shape_5.setTransform(18.3,6.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_6.setTransform(1.9,3.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAyBwIgGgBQgHgCgPgTIgGgIIgDgEQglgwgDAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABIAAAGIAAAHIABAgQAAAJADADIAIAEQAHADAAAGQAAAGgHACQgIADgUAAQgXAAgIgDQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgHQACgIAAgSIAAgTIgBgYIAAgSIAAg5QgCgOgCgDQgBgBgIgDIgFgBIgFgDIgCgEQAAgEADgDQADgCALgEIAVgGIAQgCQAEAAACADQACADAAAHIgBAeIAAAoIAAAlIAAAIQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAAAIAHgEIALgJIAOgOQAEgFAAgCQAAgCgFgCQgFgDAAgFQAAgHAHgDQAIgDAWAAQAOAAAHADQAHADAAAGQAAAHgLADQgMADgEADQgGADgNAMIgCADIgGAFIgBADQAAADANASIACACIAaAgQALANAGAEIAOAGQAKADAAAGQAAAHgHADQgHADgRAAg");
	this.shape_7.setTransform(-13.7,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhLBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQABgFAAgMIAAgKIAAgNIAAgOQAAgZgBgHQgBgHgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAGgCIAXgHIAPgDQAFAAACACQACADAAAFIAAAKIAAABIABABIABAAIAAgBIAEgDIADgDQARgQASAAQALAAALAFQAKAFAHAIQAHAJADALQADAMAAAZIAAATIAAALIgBAIQAAALACAFQACAEADACIAEACQAIADAAAFQAAAHgHACQgHACgYAAQgVAAgIgCQgHgCAAgGQAAgGAIgDIAFgCQAEgCABgHQACgHAAgQQAAgwgGgNQgHgMgQAAQgHAAgHAFQgIAFgEAIQgDAHgCAMQgBALAAAeQAAAPABAFQABAFAEACIAFACQAIADAAAGQAAAGgHACQgIADgUAAQgXAAgIgDg");
	this.shape_8.setTransform(-33,3.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAcBIIgJgIIgHAEQgSAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQAEADAAAFQAAAJgLAAQgPAAgIAHQgKAHAAANQAAANAIAHQAIAHAOAAQANAAAHgGQAGgHAAgQIAAg6QABgNgHgHQgFgIgKAAQgIAAgGAEQgGADgGAHIgEAEQgJAMgLAAQgGAAgDgEQgEgEAAgHQAAgOASgKQARgKAdAAQAQAAAMAEQANAFAGAIQAFAGACAKQACAJAAAWIAAAxQgBAIACAFQABAEAEABIAEABQAKADAAAFQAAAHgLAGQgKAGgOAAQgGAAgHgIg");
	this.shape_9.setTransform(-51.1,3.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAWBuQgIgCAAgGQAAgGAIgDIAFgCQAEgCABgHQACgGAAgRQAAgxgGgLQgHgNgQAAQgHAAgHAFQgIAFgEAHQgDAHgCAMIgBApQAAAQABAFQACAFADACIAGACQAHADAAAGQAAAGgHACQgIADgTAAQgZAAgHgDQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgGQACgHAAgRIAAgZIAAgXIgBhFQgBgRgDgDQgBgCgJgDQgKgCAAgGQAAgEAEgDQAEgDAOgFIAPgEIAOgCQAFAAADADQACADAAAHIgBAHIgBA9IAAAHIABAEIACABIADgDIAGgGQAIgIAIgEQAIgEAKAAQAaAAANARQANASAAAhIAAAPIAAAbIAAAJQAAAHACAEQABADADACIAEACQAIADAAAFQAAAHgHACQgIADgYAAQgUAAgHgDg");
	this.shape_10.setTransform(-69.9,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggBtQgIgDgBgGQAAgHAJgDQAIgDACgCQABgDACgZIABhIIgBgoIgCgZQAAgEgDgBQgCgCgHAAIgGAAQgLAAgFADQgGACgFAGIgEAKIgFALIgEAFQgDACgDAAQgFAAgBgEQgDgFAAgJQAAgUAFgNQAFgMAHAAIACAAQAMACATAAIBZAAQATAAAMgCIABAAQAJAAAEAMQAFANgBAUQAAAJgCAEQgBAFgGAAIgEgCIgFgFIgEgLIgGgKQgDgGgHgCQgFgDgMAAIgFAAQgHAAgCACQgDABgBAEIgBAZIgBAoIABBIQACAZABADQABACAJADQAIADAAAHQAAAGgJADQgIADgYAAQgXAAgJgDg");
	this.shape_11.setTransform(-89.7,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.subhead, new cjs.Rectangle(-101.6,-20.2,203.4,40.5), null);


(lib.square = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#99CC33").ss(1,1,1).p("A3UxxMAupAAAMAAAAjjMgupAAAg");
	this.shape.setTransform(0.2,0.5,1.003,1.096);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A3URxMAAAgjhMAupAAAMAAAAjhg");
	this.shape_1.setTransform(0.2,0.5,1.003,1.096);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#99CC33").ss(1,1,1).p("AAASIMAAAgkP");
	this.shape_2.setTransform(-149.9,-9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.9,-126.1,301.9,252.4);


(lib.savorysides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape.setTransform(86.8,3.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_1.setTransform(71.1,3.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhCBdQgSgVAAghQgBglAVgXQAVgYAgAAIALACQAFABACADQADAEAAAEQAAAIgKAAIgEAAIgEgBQgRAAgKAOQgLANAAAZQAAAZAMARQALAQARAAQAQAAAIgJQAJgJAAgRIAAgqIAAhGQAAgLgCgEQgCgEgGgCIgDgCQgKgCAAgGQAAgEADgDQAFgDALgEIARgFIAOgCQAGAAACADQACADAAAHIAAAIIgCBeIABBAQACAPACACIALADQAIACAAAGQAAAHgXAHIgPAEIgMABQgEAAgCgCQgBgDAAgFIAAgHIgBgDIgBgBIgEADIgIAFQgJAHgIADQgJAEgJAAQgdAAgRgVg");
	this.shape_2.setTransform(53.5,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAFgBQAEgCABgGQABgFAAgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgHgCQgKgDABgFQgBgEADgCQADgDAGgDIAYgHIAPgDQAEAAACADQACADAAAHIAAAJIgBAHIgBAmIAAABIAAAmQAAAOABAGQACAGADACIAGADQAHADAAAFQABAGgIADQgHACgUAAQgXAAgIgCgAgShNQgGgFgBgIQABgJAGgGQAIgGAKAAQAJAAAHAGQAGAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgGgGg");
	this.shape_3.setTransform(38.4,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglBvQgRgEgLgGQgGgDgEgOQgEgNAAgRQAAgIACgDQADgEAFAAQAHAAAIAOIADAGQAKASAMAHQALAIAQAAQAQAAAMgKQALgKAAgPQAAgVgsgUIgFgCQglgPgNgOQgMgOAAgVQAAgcAUgSQAVgRAggBIASACIAVAFIAGgEIAFgCQAEABADACQADACADAGQAFAJAEAKQACALAAAHQAAAGgCACQgCADgFAAQgIAAgIgLIgCgDQgJgLgKgGQgKgFgNAAQgQAAgKAIQgKAIAAAOQAAANAIAHQAJAJAgAOIAGADQAcALAMALQAIAHAFALQAEAKAAAMQAAAggWARQgWARgmAAQgTAAgQgDg");
	this.shape_4.setTransform(24.2,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhGBmQgIgHAAgJQABgJAFgFQAFgFAIAAIAGABIAGADIADAGQAFAGADAAQAHAAAJgLQAHgLAAgMQAAgNgLgZIgBgEIgZg1IgNgdQgDgGgKgEQgFgCgBgCQgCgCgBgDQABgIAHgCQAJgDAWAAQAXAAAHADQAHACABAHIgBAEIgDADIgFADQgHACAAACIAEAMIAMAfIALAcQAEAIADAAQACAAADgIIAKgXIALgfQAEgLAAgEQAAgEgJgFQgIgFgBgEQABgFAGgCQAIgDARAAQATAAAGADQAHACgBAHQAAAFgJACIgFADQgKAEgJAaIgFAMIgTAwQgaBBgPASQgQAUgXAAQgLAAgHgGg");
	this.shape_5.setTransform(-2.7,6.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_6.setTransform(-17.1,3.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgXAYggAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUASAAQAPAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_7.setTransform(-32.9,3.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgQBBQgJgQgVgxIgJgXQgLgegHgDIgEgCQgJgEAAgFQAAgHAIgCQAHgDAZABQAVgBAIADQAHACAAAHIgBAFIgDACIgFACQgGADAAAEIADALIAMAfIAMAdQAEAHACAAQACAAADgFIAGgNIARgmQAFgPAAgFIgBgFIgDgEIgFgCQgHgDAAgFQAAgFAHgDQAHgDATABQAQgBAHADQAGACAAAGQAAAGgIADIgFACQgHAEgNAeIgEAJIgGAOQgjBQgJAAQgHAAgJgPg");
	this.shape_8.setTransform(-50.4,3.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAbBIIgIgIIgHAEQgSAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQADADABAFQgBAJgJAAQgPAAgKAHQgJAHAAANQAAANAIAHQAIAHANAAQAPAAAGgGQAHgHgBgQIAAg6QAAgNgFgHQgGgIgKAAQgIAAgGAEQgHADgFAHIgEAEQgJAMgLAAQgGAAgEgEQgDgEAAgHQAAgOASgKQASgKAcAAQAQAAAMAEQAMAFAHAIQAEAGACAKQACAJAAAWIAAAxQABAIABAFQACAEADABIAEABQAKADAAAFQAAAHgLAGQgJAGgOAAQgHAAgIgIg");
	this.shape_9.setTransform(-67.4,3.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglBvQgRgEgLgGQgGgDgEgOQgEgNAAgRQAAgIACgDQADgEAFAAQAHAAAIAOIADAGQAKASAMAHQALAIAQAAQAQAAAMgKQALgKAAgPQAAgVgsgUIgFgCQglgPgNgOQgMgOAAgVQAAgcAUgSQAVgRAggBIASACIAVAFIAGgEIAFgCQAEABADACQADACADAGQAFAJAEAKQACALAAAHQAAAGgCACQgCADgFAAQgIAAgIgLIgCgDQgJgLgKgGQgKgFgNAAQgQAAgKAIQgKAIAAAOQAAANAIAHQAJAJAgAOIAGADQAcALAMALQAIAHAFALQAEAKAAAMQAAAggWARQgWARgmAAQgTAAgQgDg");
	this.shape_10.setTransform(-85.8,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.savorysides, new cjs.Rectangle(-96.6,-20.2,193.3,40.5), null);


(lib.rectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AprCeIAAk7ITXAAIAAE7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.rectangle, new cjs.Rectangle(-62,-15.7,124,31.5), null);


(lib.potatoesmc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.mashedtaters();
	this.instance.parent = this;
	this.instance.setTransform(-48.5,-49.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.potatoesmc, new cjs.Rectangle(-48.5,-49.5,97,99), null);


(lib.mainbtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E43").s().p("A/Ka4MAAAg1vMA+VAAAMAAAA1vg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A29y+MAt7AAAMAAAAl9Mgt7AAAg");
	this.shape.setTransform(0,0,1.017,1.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-125.5,301,251), null);


(lib.foodsmarket = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHBcQgIgCgFgGQgGgFgCgHQgCgJAAgXIAAhSIgPAAIgEgBIgBgEIAAgEQAAgEAQgOIAGgGIAGgFQAQgOAGAAIAEABQAAABABAAQAAABAAAAQAAABABAAQAAAAAAABIAAAdIAiAAQAEAAABABIABAGIAAAEIgBAGQgCABgDAAIggAAIgCABIgBAEIAABLQAAAVADAFQAEAEAJAAQAEAAAIgCIALgCQADAAACABQACACAAAEQAAAIgNAIQgNAIgQAAQgJAAgHgDg");
	this.shape.setTransform(96.1,2.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_1.setTransform(81.5,3.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAyBwIgGgBQgHgCgPgTIgGgIIgDgEQglgwgDAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAABIAAAGIAAAHIABAgQAAAJADADIAIAEQAHADAAAGQAAAGgHACQgIADgUAAQgXAAgIgDQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgHQACgIAAgSIAAgTIgBgYIAAgSIAAg5QgCgOgCgDQgBgBgIgDIgFgBIgFgDIgCgEQAAgEADgDQADgCALgEIAVgGIAQgCQAEAAACADQACADAAAHIgBAeIAAAoIAAAlIAAAIQAAAAABABQAAAAAAAAQAAABABAAQAAAAAAAAIAHgEIALgJIAOgOQAEgFAAgCQAAgCgFgCQgFgDAAgFQAAgHAHgDQAIgDAWAAQAOAAAHADQAHADAAAGQAAAHgLADQgMADgEADQgGADgNAMIgCADIgGAFIgBADQAAADANASIACACIAaAgQALANAGAEIAOAGQAKADAAAGQAAAHgHADQgHADgRAAg");
	this.shape_2.setTransform(64.4,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_3.setTransform(48.7,3.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAcBIIgJgIIgHAEQgSAMgTAAQgWAAgOgNQgOgNAAgVQAAgYASgNQASgOAgAAQAHAAAEACQAEADAAAFQAAAJgLAAQgPAAgIAHQgKAHAAANQAAANAIAHQAIAHAOAAQANAAAHgGQAGgHAAgQIAAg6QABgNgHgHQgFgIgKAAQgIAAgGAEQgGADgGAHIgEAEQgJAMgKAAQgHAAgDgEQgEgEAAgHQAAgOASgKQARgKAdAAQAQAAAMAEQANAFAGAIQAFAGACAKQACAJAAAWIAAAxQgBAIACAFQABAEAEABIAEABQAKADAAAFQAAAHgLAGQgKAGgOAAQgGAAgHgIg");
	this.shape_4.setTransform(33.5,3.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AA5BsQgIgDAAgGQAAgHAKgDIAGgEQADgCABgGIABgcIAAgIIAAhBIgBgmIgTAyQgtB2gKAAQgEAAgJgRQgJgQgWgyIghhMIgCA8IAAApIABAdQABAHACABIAHAEQAJADAAAHQAAAGgHADQgIADgTAAQgRAAgHgDQgIgDAAgHQAAgFAIgEQAJgEABgDQACgHACgoQACgnAAgwIAAgFQAAgQgBgFQgBgGgEgCIgHgDQgKgEAAgGQAAgGAHgDQAHgCAWAAIAWABIAGABQADACALAbIAJAWIAEALQAlBcADAAQADAAAOghQAOghASg2IADgJQAGgRAFgFQACgDAGgBIAVgBQAVAAAHACQAHADAAAGQAAAGgJADIgEACQgFADgCAGQgBAGAAAXIABBXQACAnABAGQABAEAHACIADABIAGAEQACACAAAEQAAAGgIADQgJADgZAAQgXAAgJgDg");
	this.shape_5.setTransform(10.2,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_6.setTransform(-20.8,3.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhDBdQgSgVAAghQABglAUgXQAVgYAhAAIAKACQAFABADADQACAEAAAEQAAAIgKAAIgEAAIgEgBQgRAAgKAOQgKANAAAZQAAAZALARQALAQARAAQAPAAAJgJQAJgJAAgRIAAgqIAAhGQAAgLgBgEQgDgEgFgCIgFgCQgJgCAAgGQAAgEAEgDQADgDAMgEIARgFIAOgCQAFAAADADQACADAAAHIAAAIIgBBeIAABAQACAPACACIALADQAHACAAAGQABAHgXAHIgPAEIgMABQgEAAgCgCQgBgDgBgFIAAgHIAAgDIgBgBIgFADIgGAFQgKAHgHADQgKAEgIAAQgdAAgTgVg");
	this.shape_7.setTransform(-36.9,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag3A5QgWgWAAgiQAAgiAXgXQAXgXAhAAQAiAAAUAVQAWAWAAAiQAAAigXAYQgXAYggAAQgiAAgVgXgAgcgtQgKAMAAAVQAAAeANAUQANAUASAAQAOAAAKgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgIANg");
	this.shape_8.setTransform(-56.2,3.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag4A5QgVgWAAgiQAAgiAXgXQAXgXAiAAQAgAAAWAVQAVAWAAAiQAAAigXAYQgWAYgiAAQggAAgXgXgAgdgtQgJAMAAAVQAAAeANAUQANAUASAAQAOAAAKgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgPAAgKANg");
	this.shape_9.setTransform(-74.4,3.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhNBuQgJgDABgHQgBgGAJgDQAHgDACgCQACgEABgWIABg8IgBg4QgBgYgCgCQgCgCgHgEQgJgEABgGQgBgGAIgCQAGgCAbAAIBdAAIAQgCIAHgBIAEABIADACQADAFADALQADALgBAHQABAHgDAEQgDAEgEgBQgGAAgFgKIgFgIQgDgEgIgCQgGgDgLAAIgUAAQgPAAgHABQgIACgDAEQgCADgBAKIgBAeIAAAMQAAAHABACQABACAEAAIAZAAQAMAAAFgEQAFgDACgKIAAgDQACgQAIAAQAHAAACAJQADAIAAAeQAAAcgDAJQgCAHgHABQgIAAgCgQIAAgDQgCgKgFgEQgFgDgMAAIgYAAQgFAAgBADQgBACAAAKIAAAMIABArQABAJACACIAHADQAKAEgBAGQAAAHgIADQgIADgYAAQgZAAgIgDg");
	this.shape_10.setTransform(-93.1,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.foodsmarket, new cjs.Rectangle(-104.6,-20.2,209.3,40.5), null);


(lib.FindaStore = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAqIAAhJIgbAAIAAgLIBBAAIAAALIgbAAIAABJg");
	this.shape.setTransform(41,-0.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAVAqIgshEIgBAAIAABEIgLAAIAAhUIAQAAIArBEIAAAAIAAhEIAMAAIAABUg");
	this.shape_1.setTransform(33,-0.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbAqIAAhUIA1AAIAAALIgqAAIAAAZIAoAAIAAAJIgoAAIAAAdIAsAAIAAAKg");
	this.shape_2.setTransform(25,-0.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFAqIghhUIANAAIAZBFIAAAAIAahFIANAAIgiBUg");
	this.shape_3.setTransform(17.3,-0.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAqIAAhUIA2AAIAAALIgqAAIAAAZIAnAAIAAAJIgnAAIAAAdIArAAIAAAKg");
	this.shape_4.setTransform(10.1,-0.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAVAqIgshEIAAAAIAABEIgMAAIAAhUIAPAAIArBEIABAAIAAhEIAMAAIAABUg");
	this.shape_5.setTransform(-1.3,-0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAdAqIgJgVIgnAAIgJAVIgNAAIAlhUIAJAAIAlBUgAAQALIgQgmIgPAmIAfAAg");
	this.shape_6.setTransform(-10.2,-0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglAqIAAhUIAdAAQAIABAIACQAIADAHAEQAGAFAEAJQADADAAAGIABAJIgBAKQAAAFgDAEIgFAHIgFAGQgHAFgIADQgKACgGAAgAgZAgIAPAAQAIAAAGgCQAGgDAFgEQAEgDADgHIACgGIAAgHIAAgGIgCgHQgDgGgEgEQgFgEgGgCQgGgCgIAAIgPAAg");
	this.shape_7.setTransform(-21.8,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAVAqIgshEIgBAAIAABEIgLAAIAAhUIAQAAIAqBEIABAAIAAhEIAMAAIAABUg");
	this.shape_8.setTransform(-31.2,-0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgFAqIAAhUIALAAIAABUg");
	this.shape_9.setTransform(-37.5,-0.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgZAqIAAhUIA0AAIAAALIgpAAIAAAaIAlAAIAAAJIglAAIAAAmg");
	this.shape_10.setTransform(-42.2,-0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.FindaStore, new cjs.Rectangle(-47.9,-10.2,94.5,18.8), null);


(lib.deliciousdesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape.setTransform(121.3,3.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHBcQgIgCgFgGQgGgFgCgHQgCgJAAgXIAAhSIgPAAIgEgBIgBgEIAAgEQAAgEAQgOIAGgGIAGgFQAQgOAGAAIAEABQAAABABAAQAAABAAAAQABABAAAAQAAAAAAABIAAAdIAiAAQAEAAABABIABAGIAAAEIgBAGQgCABgDAAIggAAIgCABIgBAEIAABLQAAAVADAFQAEAEAJAAQAEAAAIgCIALgCQADAAACABQACACAAAEQAAAIgNAIQgNAIgQAAQgJAAgHgDg");
	this.shape_1.setTransform(108.9,2.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AguBMQgHgCAAgHQAAgFAHgDIAEgCQAEgCACgFQACgFAAgMIgBgKIAAgNIAAgJQAAgbgBgJQgBgIgDgCIgIgDQgJgDAAgFQAAgDADgDQADgDAHgCIAUgHIAOgDQAHAAADAVIAAADIABABQAIgNAIgGQAJgHAJAAQAKAAAHAHQAGAGAAALQAAALgFAGQgFAGgJAAIgHgBIgHgFIgDgGQgCgEgCAAQgKAAgEAPQgEAOAAAuQAAANABAHQACAHAEACIAGACQAKADAAAGQAAAGgJACQgJADgUAAQgXAAgIgDg");
	this.shape_2.setTransform(97.4,3.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_3.setTransform(82.6,3.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_4.setTransform(67.3,3.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_5.setTransform(53.5,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_6.setTransform(38.4,3.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghBvIgTgBIgNABIgMAAQgTAAgGgDQgGgCAAgHQAAgFAIgEQAIgDACgCQACgDABgXIABg7IgBg5QgBgXgCgDQgCgCgIgEQgIgDAAgGQAAgGAHgDQAGgCASAAIAOAAIAPAAIAUAAIASgBQA4AAAgAeQAfAdAAA2QAAA1ggAcQggAbg8AAgAghhWQgHACgCAFQgCAFgBASIgBAvIABA6QABAYACAFQACAFAKADQAKADAOAAQAjAAARgVQASgVAAgrQAAgtgUgYQgUgYgmAAQgMAAgHADg");
	this.shape_7.setTransform(17.8,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLBQIgQgDIgFADIgFABIgDgBIgDgCQgFgFgFgMQgEgMAAgMQAAgFADgDQACgDAEAAQAHAAAIAMIAFAJQAFAHAIADQAIAEAIAAQAKAAAGgFQAGgGAAgIQAAgNgZgMIgJgFQgYgMgIgJQgIgKAAgOQAAgUANgNQAOgNAXAAIAKABIAKACIAIgDIAEgBQAIAAAHAMQAHAMAAAOQAAAFgCADQgCADgFAAQgDAAgEgDQgDgDgFgHQgGgKgGgDQgGgEgIAAQgIAAgGAFQgFAFAAAIQAAAHAFAFQAGAGASAJIACABQArAUAAAZQAAAWgRAOQgQAPgZAAg");
	this.shape_8.setTransform(-10,3.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAhBOQgCgCAAgFIAAgLIAAgBIgBAAQgCAAgDAEIgCACQgIAHgJAEQgIAEgLAAQgMAAgKgFQgKgEgHgIQgHgJgDgMQgDgMAAggIAAgLIAAgLIAAgDQAAgNgCgDQgCgEgFgCIgGgCQgJgCAAgGQAAgDADgDQADgDALgDIAVgGIAQgCQAEAAACADQACADAAAHIAAAGIgCA5QAAAfAHAMQAGAMAQAAQARAAAHgQQAIgPAAglIAAgMQAAgMgCgDQgCgEgFgCIgGgCQgJgCAAgGQAAgDADgDQADgCALgEIAVgGIAQgCQAEAAACADQACADAAAHIAAAIIgCA/IAAAaIABAKQABAGAIADIADABQAJADAAAFQAAAEgDACIgJAGIgWAHQgLACgFAAQgFAAgCgCg");
	this.shape_9.setTransform(-26.3,3.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag4A5QgVgWAAgiQAAgiAXgXQAXgXAiAAQAgAAAWAVQAVAWAAAiQAAAigXAYQgWAYgiAAQggAAgXgXgAgdgtQgJAMAAAVQAAAeANAUQANAUARAAQAQAAAJgMQAJgNAAgVQAAgdgNgUQgNgVgRAAQgQAAgJANg");
	this.shape_10.setTransform(-44.4,3.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAEgBQAEgCACgGQACgFgBgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgHgCQgKgDABgFQgBgEADgCQADgDAGgDIAYgHIAPgDQAEAAACADQACADAAAHIAAAJIgBAHIgBAmIAAABIAAAmQAAAOABAGQABAGAEACIAFADQAIADAAAFQABAGgIADQgIACgUAAQgWAAgIgCgAgShNQgHgFAAgIQAAgJAHgGQAIgGAKAAQAJAAAHAGQAGAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgGgGg");
	this.shape_11.setTransform(-58,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgwA6QgWgXAAghQAAgiAXgYQAXgXAiAAQAZAAASANQASANAAASQAAAHgFAFQgFAEgIAAQgIAAgEgEQgFgDgFgNQgFgLgGgEQgGgFgKAAQgQAAgKAOQgKANAAAYQAAAaAOARQAOARAVAAQAIAAAHgCQAHgCAFgEIAGgEQAIgHAFAAQADAAACACQACACAAADQAAAEgDAGQgDAFgFAEQgNALgMAFQgOAFgPAAQgfAAgWgWg");
	this.shape_12.setTransform(-70.6,3.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbBuQgHgDAAgHQAAgFAHgDIAFgBQAEgCABgGQABgFAAgLIAAgLIAAgMIAAgQQAAgYgBgHQgBgHgDgCIgIgCQgJgDAAgFQABgEACgCQADgDAGgDIAYgHIAPgDQAFAAABADQACADAAAHIAAAJIAAAHIgCAmIAAABIAAAmQAAAOACAGQAAAGAEACIAGADQAHADABAFQAAAGgIADQgHACgUAAQgXAAgIgCgAgThNQgFgFgBgIQABgJAGgGQAIgGAKAAQAJAAAGAGQAHAFAAAJQAAAIgHAGQgHAGgKAAQgKAAgHgGg");
	this.shape_13.setTransform(-83.4,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZBuQgIgCABgHQgBgFAHgDIAHgEQADgCACgKIABgeIAAgYIgBgcIAAgMQAAgngBgLQgCgLgDgCIgJgDQgKgDAAgFQAAgEADgDQADgCALgEIAUgGIAQgCQAEAAACADQACADAAAHIAAAMQgCA3AAA2IABA1QABALACADIAJAEQAHADAAAGQAAAGgIACQgHADgUAAQgWAAgIgDg");
	this.shape_14.setTransform(-92.8,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgxA6QgWgXAAghQAAgjAWgXQAXgXAiAAQAdAAASARQARARAAAcQAAAKgDADQgCADgMAAIg6AAQgFAAgDgDQgDgCAAgEQAAgEADgCQADgDAFAAIAfAAIAIgBQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgPgKgKQgKgLgOAAQgSAAgJARQgJAPAAAXQAAAXANASQAMARATAAQALAAAIgCQAHgDAIgFIAFgEQAIgHAEAAQAEAAACACQACADAAADQAAADgEAGQgDAFgHAFQgNALgNAFQgMAFgPAAQgfAAgWgWg");
	this.shape_15.setTransform(-105.4,3.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AghBvIgTgBIgNABIgMAAQgTAAgGgDQgGgCAAgHQAAgFAIgEQAIgDACgCQACgDABgXIABg7IgBg5QgBgXgCgDQgCgCgIgEQgIgDAAgGQAAgGAHgDQAGgCASAAIAOAAIAPAAIAUAAIASgBQA4AAAgAeQAfAdAAA2QAAA1ggAcQggAbg8AAgAghhWQgHACgCAFQgCAFgBASIgBAvIABA6QABAYACAFQACAFAKADQAKADAOAAQAjAAARgVQASgVAAgrQAAgtgUgYQgUgYgmAAQgMAAgHADg");
	this.shape_16.setTransform(-126,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.deliciousdesserts, new cjs.Rectangle(-139.6,-20.2,270.4,40.5), null);


(lib.datemc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAGQgCgDAAgDQgBgDADgCQACgDADAAQAEAAACADQADACAAADQAAADgDADQgCADgEgBQgDABgCgDg");
	this.shape.setTransform(135,3.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAdAsIgDgBQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgoIgBgBIgCAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABgBAAIgNAWQgCACgCABIgCgBIgCgCIgNgWQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgCAAIgBACIAAAnQgBADgDAAIgFABIgDAAIgCgBIgBgBIgBgCIAAhPQAAgBABgBQAAAAAAgBQABAAAAAAQABAAAAgBIAFAAIADAAQABABAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAWAiQABADACAAIACAAIADgDIAVgiQACgDAFgBIADABQAAAAABAAQAAAAABABQAAAAAAAAQABABAAABIAABQIgBADIgDABIgDAAg");
	this.shape_1.setTransform(128,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFAGQgCgDAAgDQgBgDADgCQACgDADAAQAEAAACADQADACAAADQAAADgDADQgCADgEgBQgDABgCgDg");
	this.shape_2.setTransform(120.8,3.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeAtQgEAAgCgEIAAhSIACgCIACgBIAmAAQAGAAAFACQAGACAEAEQAFADACAFQADAFAAAHIgBAEIgBAEQgDAIgGAEQgGAEgHABQgHABgHAAIgPAAIgBAAIgBABIgCADIAAAcIgCACIgCAAIgDABgAgSgbQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAOIACADIACABIAWAAIAFgBIAEgCQADgBABgDIABgFIgBgFIgDgDIgFgDIgEAAIgWAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_3.setTransform(114.8,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAHAuIgCgDIAAgOIgBgEQgBAAAAAAQAAgBgBAAQAAAAgBAAQAAAAgBAAIgcAAIgDgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIABgEIAag6IADgCIADgBIACAAIADABIACACIAAADIgBAEIgDAHIgDAKIgFAKIgDAIIgCADIgBACIAAABIABACIADABIADAAIAEAAIADgBQABAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAAgNQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIADgBIACAAIACABIACAAIACACIAAACIAAAMIABAEQAAAAABAAQAAABAAAAQABAAAAAAQABAAAAAAIAHAAQACACABACIAAAFQAAABAAABQAAABAAAAQgBABAAAAQAAAAAAAAIgEACIgDAAIgEABIgBACIgBACIABAJIgBAFQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgHAAg");
	this.shape_4.setTransform(102,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AALAHIgWAAIgCgBIgBgBIAAgDIAAgCIAAgBIAAgDIABgBIACgBIAWAAIACABIABABIABADIAAABIAAAEIgDADg");
	this.shape_5.setTransform(96,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcAtIgDgBIgCgDIAAgEIAAgEIABgEIACgCIAmgeIAGgGQACgDAAgFQAAgDgCgCIgEgFIgFgCIgFgBQgFAAgEACIgFAEIgFAEIgEABIgCAAIgDgCIgDgCIgBgDIABgDIAHgHIAHgEQAIgEAJAAIAMACQAGACAEADQAFAEACAFQADAFAAAHQAAAHgEAGQgFAGgGAEIgWASIgBABIAAABQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAIAhAAIACABIACACIAAADIABACIgBAFQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_6.setTransform(89.7,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAHAsIgEAAIgDgCIAAgCIAAg3IAAgCIgDgBQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCABQgDAAgCgDIgCgFIABgEIADgCIADgCIADgDIAFgDIAEgDIAFgCIACgBIADABIACADIAABPQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIgEABg");
	this.shape_7.setTransform(82.8,-0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAdAsIgDgBQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgoIgBgBIgCAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAABAAAAIgPAWQgBACgCABIgDgBIgCgCIgMgWQAAAAAAgBQgBAAAAAAQAAAAAAAAQgBAAAAAAIgDAAIAAACIAAAnQgBADgDAAIgFABIgCAAIgCgBIgCgBIgBgCIAAhPQAAgBABgBQAAAAAAgBQABAAAAAAQAAAAABgBIAFAAIADAAQAAABABAAQAAAAABAAQAAAAAAABQAAAAAAABIAVAiQACADACAAIACAAIACgDIAWgiQACgDAEgBIAEABQAAAAABAAQAAAAAAABQABAAAAAAQABABAAABIAABQIgBADIgCABIgEAAg");
	this.shape_8.setTransform(71.9,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIAtIgJgDIgIgEIgHgGQgHgFgDgJIgDgIIgBgKIABgIIADgJQADgJAHgGIAHgFIAIgEIAJgDIAIgBIAKABIAJADQAIAEAGAFQAHAGAEAJQADAIAAAJIgBAKIgCAIQgEAJgHAFQgGAHgIADIgJADIgKABIgIgBgAgKgbQgGACgEAEQgEAFgDAFQgCAGAAAFQAAAHACAFQADAGAEADQAEAEAGADQAFACAFABQAGgBAFgCQAGgDAEgEQAEgDADgGQACgFAAgHQAAgFgCgGQgDgFgEgFQgEgEgGgCQgFgCgGgBQgFABgFACg");
	this.shape_9.setTransform(61.4,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAWAtIgCgBIgCgBIgBgBIgPgXIgCgDIgEgBIgLAAIgDABIgBADIAAAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgEABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBgBAAIAAhQQABgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAFACQAGADAEADQAFAEACAGQADAFgBAHQAAAIgCAEQgDAEgEADIgGAFQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIAAACIAEAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAGAAIAGgDQACgBABgDQABgDAAgEQAAgHgEgEIgGgCIgGgBIgSAAIgDABg");
	this.shape_10.setTransform(51.8,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgaAtIgDAAQgDAAgBgDIAAhRQAAgBAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIA8AAIABABIACADIAAADIAAACIgBAEQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAABIgrAAIgDABIgCADIAAALIABADIADABIAcAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIABADIAAADIAAACIAAADQAAABgBAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgbAAIgCAAIgBABIgCACIgBABIAAAgIgCACIgCABg");
	this.shape_11.setTransform(43.6,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcAtIgDgBIgCgDIAAgEIAAgEIABgEIACgCIAmgeIAGgGQACgDAAgFQAAgDgCgCIgEgFIgFgCIgFgBQgFAAgEACIgFAEIgFAEIgEABIgCAAIgDgCIgDgCIgBgDIABgDIAHgHIAHgEQAIgEAJAAIAMACQAGACAEADQAFAEACAFQADAFAAAHQAAAHgEAGQgFAGgGAEIgWASIgBABIAAABQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAIAhAAIACABIACACIAAADIABACIgBAFQAAAAgBABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_12.setTransform(30.7,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAHAsIgEAAIgCgCIgBgCIAAg3IAAgCIgDgBQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCABQgDAAgCgDIgCgFIABgEIACgCIAEgCIADgDIAFgDIAEgDIAFgCIACgBIADABIACADIAABPQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIgDABg");
	this.shape_13.setTransform(23.7,-0.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAKAHIgUAAIgDgBIgBgBIgBgDIAAgCIAAgBIABgDIABgBIADgBIAVAAIACABIACABIAAADIABABIgBAEIgDADg");
	this.shape_14.setTransform(19.8,-0.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGAsIgDAAIgCgCIgBgCIAAg3IAAgCIgDgBQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCABQgDAAgCgDIgBgFIAAgEIACgCIAEgCIADgDIAFgDIAEgDIAFgCIACgBIADABIABADIAABPQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgDABg");
	this.shape_15.setTransform(14.6,-0.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAGAsIgDAAIgCgCQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAAg3IgBgCIgCgBQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAAAABIgEABQgCAAgCgDIgBgFIABgEIABgCIADgCIAFgDIAEgDIAEgDIAEgCIADgBIADABIABADIAABPQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgEABg");
	this.shape_16.setTransform(9.9,-0.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgFAGQgCgDAAgDQgBgDADgCQACgDADAAQAEAAACADQADACAAADQAAADgDADQgCADgEgBQgDABgCgDg");
	this.shape_17.setTransform(2,3.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAArIgDgGIgFgKIgGgMIgFgOIgHgNIgEgMIgEgJIgCgEIABgDIADgCIAEgBIACAAIAFABIACADIASArIABABIAAABQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIASgsQABAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIADgBIADAAIAEABIACACIABADIgBAEIgDAJIgGAMIgGANIgGAPIgGANIgDAKIgDAFIgBABIgBABQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBg");
	this.shape_18.setTransform(-4,-0.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgIAtIgJgDIgIgEIgHgGQgHgFgDgJIgDgIIgBgKIABgIIADgJQADgJAHgGIAHgFIAIgEIAJgDIAIgBIAKABIAJADQAIAEAGAFQAHAGAEAJQADAIAAAJIgBAKIgCAIQgEAJgHAFQgGAHgIADIgJADIgKABIgIgBgAgKgbQgGACgEAEQgEAFgDAFQgCAGAAAFQAAAHACAFQADAGAEADQAEAEAGADQAFACAFABQAGgBAFgCQAGgDAEgEQAEgDADgGQACgFAAgHQAAgFgCgGQgDgFgEgFQgEgEgGgCQgFgCgGgBQgFABgFACg");
	this.shape_19.setTransform(-13.4,-0.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAaAuQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAgBgBIgjgxIgDgBIgCABIgBACIAAAtIgDADIgFABIgFAAQgBgBAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAhSIABgDIACgBIADgBIADAAQAEABACADIAjAuIACABIACAAIABgBIAAgtIACgCIADgBIADAAIADAAQAEAAABADIAABUIgCADIgEABg");
	this.shape_20.setTransform(-23.5,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.datemc, new cjs.Rectangle(-30.1,-8.4,169.6,16.9), null);


(lib.ctahovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("ApYCNIAAkZISxAAIAAEZg");
	this.shape.setTransform(-5,0,1.031,1.116);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctahovervideo, new cjs.Rectangle(-67,-15.7,124.1,31.5), null);


(lib.cranberriesmc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.cranberries();
	this.instance.parent = this;
	this.instance.setTransform(-39,-37.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cranberriesmc, new cjs.Rectangle(-39,-37.5,78,75), null);


(lib.brussels_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.brussels();
	this.instance.parent = this;
	this.instance.setTransform(-54,-54);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.brussels_1, new cjs.Rectangle(-54,-54,108,108), null);


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.WFM_Logo_White_RGBai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0,0,1,1,0,0,0,175,175);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175,-175,350,350);


(lib.trynewsamples = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.trynewsamplesforyourfeast("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.trynewsamples, new cjs.Rectangle(-129.8,-36.9,242.8,73.9), null);


(lib.thanksgiving = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.subhead();
	this.instance.parent = this;
	this.instance.setTransform(-56.2,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.thanksgiving, new cjs.Rectangle(-157.8,-20.2,203.4,40.5), null);


(lib.ctahover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctahovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67,-15.7,124.1,31.5);


// stage content:
(lib.squareatasteofseven = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_35 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		
		console.log("this frame works");
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_274 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(35).call(this.frame_35).wait(239).call(this.frame_274).wait(6));

	// button
	this.btn_main = new lib.mainbtn();
	this.btn_main.parent = this;
	this.btn_main.setTransform(150.1,125,0.752,0.727,0,0,0,0.1,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(280));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(280));

	// fade-from-black
	this.instance_1 = new lib.square("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(149.5,124.2);
	this.instance_1.filters = [new cjs.ColorFilter(1, 1, 1, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-153,-128,306,256);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(271));

	// logo
	this.instance_2 = new lib.whitelogo("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(250.8,32.8,0.003,0.003);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({startPosition:0},0).to({regX:0.4,regY:0.4,scaleX:0.24,scaleY:0.24,y:32.9,alpha:1,mode:"independent"},6,cjs.Ease.get(1)).to({regX:0.2,regY:0.2,scaleX:0.22,scaleY:0.22,mode:"synched",startPosition:0},7,cjs.Ease.get(1)).wait(258));

	// date-mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AtWMbIAAiNIclAAIAACNg");
	mask.setTransform(97.5,79.5);

	// Date
	this.instance_3 = new lib.datemc();
	this.instance_3.parent = this;
	this.instance_3.setTransform(42,152.4);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(27).to({x:-18.4},0).to({x:48,alpha:1},10,cjs.Ease.get(1)).to({x:44},8,cjs.Ease.get(1)).wait(235));

	// tasting event mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("AuIFXIAAiMIeKAAIAACMg");
	mask_1.setTransform(102.6,34.3);

	// Tasting Event Near You
	this.instance_4 = new lib.tastingeventmc();
	this.instance_4.parent = this;
	this.instance_4.setTransform(102.9,61.4);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({x:-79.3},0).to({x:108.9,alpha:1},10,cjs.Ease.get(1)).to({x:104.9},8,cjs.Ease.get(1)).wait(253));

	// find-a-store-mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("AmHPeIAAjcIRJAAIAADcg");
	mask_2.setTransform(70.6,99);

	// Find a Store
	this.instance_5 = new lib.FindaStore();
	this.instance_5.parent = this;
	this.instance_5.setTransform(77.2,187.1);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(35).to({x:-29.1},0).to({x:81.2,alpha:1},10,cjs.Ease.get(1)).to({x:77.2},8,cjs.Ease.get(1)).wait(227));

	// cta-rollover
	this.cta_rollover = new lib.ctahover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(82.1,186.7);

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(280));

	// cta-rectangle-mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("AqSQLIAAmaIW8AAIAAGag");
	mask_3.setTransform(81,103.5);

	// cta-rectangle
	this.instance_6 = new lib.rectangle();
	this.instance_6.parent = this;
	this.instance_6.setTransform(77.1,186.6);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(35).to({x:-51.5},0).to({x:82.1,alpha:1},10,cjs.Ease.get(1)).to({x:77.1},8,cjs.Ease.get(1)).wait(227));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("A1UC+IAAl7MAqpAAAIAAF7g");
	mask_4.setTransform(148.5,91.1);

	// A Taste of
	this.instance_7 = new lib.tophead();
	this.instance_7.parent = this;
	this.instance_7.setTransform(93.1,90);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(15).to({x:-201.8},0).to({x:103.1,alpha:1},10,cjs.Ease.get(1)).to({x:93.1},8,cjs.Ease.get(1)).wait(178).to({alpha:0},5).wait(64));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("A1UC+IAAl7MAqpAAAIAAF7g");
	mask_5.setTransform(148.5,91.1);

	// Whole
	this.instance_8 = new lib.whole();
	this.instance_8.parent = this;
	this.instance_8.setTransform(227,90);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(15).to({x:-67.9},0).to({x:237,alpha:1},10,cjs.Ease.get(1)).to({x:227},8,cjs.Ease.get(1)).wait(68).to({alpha:0},5).wait(174));

	// mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("A0XLUIAAl7MAqoAAAIAAF7g");
	mask_6.setTransform(142.5,72.5);

	// foods-market
	this.text = new cjs.Text("", "30px 'CooperBTforWFM-Medium'", "#FFFFFF");
	this.text.lineHeight = 40;
	this.text.parent = this;
	this.text.setTransform(33.6,89.9);

	this.instance_9 = new lib.foodsmarket();
	this.instance_9.parent = this;
	this.instance_9.setTransform(116.4,123.7);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.text,this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_9},{t:this.text}]}).to({state:[{t:this.instance_9}]},15).to({state:[{t:this.instance_9}]},10).to({state:[{t:this.instance_9}]},8).to({state:[{t:this.instance_9}]},68).to({state:[{t:this.instance_9}]},5).wait(174));
	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(15).to({x:-178.5},0).to({x:126.4,alpha:1},10,cjs.Ease.get(1)).to({x:116.4},8,cjs.Ease.get(1)).wait(68).to({alpha:0},5).wait(174));

	// try-new-samples-for-your-feast
	this.instance_10 = new lib.trynewsamplesforyourfeast("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(144.9,106.8);
	this.instance_10.alpha = 0;

	this.instance_11 = new lib.trynewsamples();
	this.instance_11.parent = this;
	this.instance_11.setTransform(142.9,106.8);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_10}]}).to({state:[{t:this.instance_11}]},236).to({state:[{t:this.instance_11}]},10).wait(34));
	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(236).to({_off:false},0).to({alpha:1},10).wait(34));

	// Thanksgiving
	this.instance_12 = new lib.subhead();
	this.instance_12.parent = this;
	this.instance_12.setTransform(116.7,123.7);
	this.instance_12.alpha = 0;

	this.instance_13 = new lib.thanksgiving();
	this.instance_13.parent = this;
	this.instance_13.setTransform(172.9,123.7);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.text_1 = new cjs.Text("", "30px 'CooperBTforWFM-Medium'", "#FFFFFF");
	this.text_1.lineHeight = 40;
	this.text_1.parent = this;
	this.text_1.setTransform(5.6,87.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_12}]}).to({state:[{t:this.instance_13}]},171).to({state:[{t:this.instance_13}]},10).to({state:[{t:this.instance_13}]},30).to({state:[{t:this.instance_13},{t:this.text_1}]},5).wait(64));
	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(171).to({_off:false},0).to({alpha:1},10).wait(30).to({alpha:0},5).wait(64));

	// delicious-desserts
	this.instance_14 = new lib.deliciousdesserts();
	this.instance_14.parent = this;
	this.instance_14.setTransform(154.7,123.7);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(141).to({alpha:1},10).wait(20).to({alpha:0},5).wait(104));

	// savory-sides
	this.instance_15 = new lib.savorysides();
	this.instance_15.parent = this;
	this.instance_15.setTransform(108.5,123.7);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(101).to({alpha:1},10).wait(30).to({alpha:0},5).wait(134));

	// brussels
	this.instance_16 = new lib.brussels_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(181,-11);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(60).to({alpha:1},10).wait(210));

	// potatoes
	this.instance_17 = new lib.potatoesmc();
	this.instance_17.parent = this;
	this.instance_17.setTransform(106.5,229.5);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(55).to({alpha:1},10).wait(215));

	// cranberries
	this.instance_18 = new lib.cranberriesmc();
	this.instance_18.parent = this;
	this.instance_18.setTransform(31,-11.5);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(65).to({alpha:1},10).wait(205));

	// turkey-meal-plate
	this.instance_19 = new lib.turkeymealplatemc();
	this.instance_19.parent = this;
	this.instance_19.setTransform(248.5,210.5);
	this.instance_19.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(70).to({alpha:1},10).wait(200));

	// table-still
	this.instance_20 = new lib.tablestillatasteof_1("synched",0);
	this.instance_20.parent = this;
	this.instance_20.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(280));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(142,60,335,354);
// library properties:
lib.properties = {
	id: '92879F2740E34FB9890B82961B713FEA',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['92879F2740E34FB9890B82961B713FEA'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;